# mlFlow Registry QA & Prod pipeline 

trigger:
- master2

pool:
  vmImage: 'ubuntu-18.04'

steps:
- task: UsePythonVersion@0
  displayName: 'Use Python 3.7'
  inputs:
    versionSpec: 3.7

- script: |
    pip install pytest requests setuptools wheel
    pip install -U databricks-cli
    dbfs ls
  displayName: 'Load Python Dependencies'

- checkout: self
  persistCredentials: true
  clean: true

- script: git fetch && git checkout dev
  displayName: 'Get Latest Branch'


- script: |
    databricks workspace import $BUILD_SOURCESDIRECTORY/"notebooks/Users/oliver.koernig@databricks.com/ML/deploy/deploy_azure_ml_model.py" "/Demo/Test/deploy_azure_ml_model"  --language PYTHON -o
  displayName: 'Import ML Deploy Notebook'
- task: PythonScript@0
  inputs:
    scriptSource: 'filePath'
    scriptPath: '$(Build.Repository.LocalPath)/cicd-scripts/executenotebook.py'
    arguments: '--shard $(DATABRICKS_HOST) --token $(DATABRICKS_TOKEN) --cluster $(EXISTING_CLUSTER_ID) --localpath $(Build.Repository.LocalPath)/notebooks/Users/oliver.koernig@databricks.com/ML/deploy --workspacepath /Demo/Test --outfilepath /home/vsts/work/1/s/notebooks/Users/oliver.koernig@databricks.com --params model_name=$(model_name)'
  displayName: 'Deploy mlFlow Model from Registry to Azure ML for Testing'

- powershell: |
    tree "$(System.DefaultWorkingDirectory)" /F
  displayName: 'Treeview of System.DefaultWorkingDirectory'
- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)/model'
    targetFolder: '$(Build.ArtifactStagingDirectory)/model'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'model'
